# Generated by Django 4.2.6 on 2023-10-17 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Название")),
                ("title", models.CharField(max_length=100, verbose_name="Текст меню")),
                (
                    "url",
                    models.CharField(blank=True, max_length=100, verbose_name="URL"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="menu.menuitem",
                        verbose_name="Предыдущий узел",
                    ),
                ),
            ],
            options={
                "verbose_name": "Элемент меню",
                "verbose_name_plural": "Элементы меню",
                "ordering": ("title",),
            },
        ),
    ]
